/**
 * This file was generated by Apache Newt (incubating) version: 1.0.0-dev
 */

#ifndef H_MYNEWT_SYSCFG_
#define H_MYNEWT_SYSCFG_

/**
 * This macro exists to ensure code includes this header when needed.  If code
 * checks the existence of a setting directly via ifdef without including this
 * header, the setting macro will silently evaluate to 0.  In contrast, an
 * attempt to use these macros without including this header will result in a
 * compiler error.
 */
#define MYNEWT_VAL(x)                           MYNEWT_VAL_ ## x



/*** encoding/cborattr */
#ifndef MYNEWT_VAL_CBORATTR_MAX_SIZE
#define MYNEWT_VAL_CBORATTR_MAX_SIZE (512)
#endif

/*** kernel/os */
#ifndef MYNEWT_VAL_FLOAT_USER
#define MYNEWT_VAL_FLOAT_USER (0)
#endif

#ifndef MYNEWT_VAL_MSYS_1_BLOCK_COUNT
#define MYNEWT_VAL_MSYS_1_BLOCK_COUNT (12)
#endif

#ifndef MYNEWT_VAL_MSYS_1_BLOCK_SIZE
#define MYNEWT_VAL_MSYS_1_BLOCK_SIZE (292)
#endif

/*** net/oic */
#ifndef MYNEWT_VAL_OC_APP_RESOURCES
#define MYNEWT_VAL_OC_APP_RESOURCES (3)
#endif

#ifndef MYNEWT_VAL_OC_CLIENT
#define MYNEWT_VAL_OC_CLIENT (0)
#endif

#ifndef MYNEWT_VAL_OC_CONCURRENT_REQUESTS
#define MYNEWT_VAL_OC_CONCURRENT_REQUESTS (2)
#endif

#ifndef MYNEWT_VAL_OC_DEBUG
#define MYNEWT_VAL_OC_DEBUG (1)
#endif

#ifndef MYNEWT_VAL_OC_LOGGING
#define MYNEWT_VAL_OC_LOGGING (1)
#endif

#ifndef MYNEWT_VAL_OC_MAX_PAYLOAD
#define MYNEWT_VAL_OC_MAX_PAYLOAD (256)
#endif

#ifndef MYNEWT_VAL_OC_MAX_PAYLOAD_SIZE
#define MYNEWT_VAL_OC_MAX_PAYLOAD_SIZE (1120)
#endif

#ifndef MYNEWT_VAL_OC_NUM_DEVICES
#define MYNEWT_VAL_OC_NUM_DEVICES (1)
#endif

#ifndef MYNEWT_VAL_OC_NUM_REP_OBJECTS
#define MYNEWT_VAL_OC_NUM_REP_OBJECTS (32)
#endif

#ifndef MYNEWT_VAL_OC_SEPARATE_RESPONSES
#define MYNEWT_VAL_OC_SEPARATE_RESPONSES (1)
#endif

/* Overridden by targets/ocf_sample_ip (defined by net/oic) */
#ifndef MYNEWT_VAL_OC_SERVER
#define MYNEWT_VAL_OC_SERVER (1)
#endif

#ifndef MYNEWT_VAL_OC_TRANSPORT_GATT
#define MYNEWT_VAL_OC_TRANSPORT_GATT (1)
#endif

/* Overridden by targets/ocf_sample_ip (defined by net/oic) */
#ifndef MYNEWT_VAL_OC_TRANSPORT_IP
#define MYNEWT_VAL_OC_TRANSPORT_IP (1)
#endif

#ifndef MYNEWT_VAL_OC_TRANSPORT_IPV4
#define MYNEWT_VAL_OC_TRANSPORT_IPV4 (1)
#endif

#ifndef MYNEWT_VAL_OC_TRANSPORT_IPV6
#define MYNEWT_VAL_OC_TRANSPORT_IPV6 (1)
#endif

/* Overridden by targets/ocf_sample_ip (defined by net/oic) */
#ifndef MYNEWT_VAL_OC_TRANSPORT_SERIAL
#define MYNEWT_VAL_OC_TRANSPORT_SERIAL (0)
#endif

/*** sys/log/full */
#ifndef MYNEWT_VAL_LOG_CLI
#define MYNEWT_VAL_LOG_CLI (0)
#endif

#ifndef MYNEWT_VAL_LOG_CONSOLE
#define MYNEWT_VAL_LOG_CONSOLE (1)
#endif

#ifndef MYNEWT_VAL_LOG_FCB
#define MYNEWT_VAL_LOG_FCB (0)
#endif

#ifndef MYNEWT_VAL_LOG_LEVEL
#define MYNEWT_VAL_LOG_LEVEL (0)
#endif

#ifndef MYNEWT_VAL_LOG_NEWTMGR
#define MYNEWT_VAL_LOG_NEWTMGR (0)
#endif

/*** sys/shell */
#ifndef MYNEWT_VAL_SHELL_DEBUG
#define MYNEWT_VAL_SHELL_DEBUG (0)
#endif

#ifndef MYNEWT_VAL_SHELL_MAX_INPUT_LEN
#define MYNEWT_VAL_SHELL_MAX_INPUT_LEN (256)
#endif

/* Overridden by apps/ocf_sample (defined by sys/shell) */
#ifndef MYNEWT_VAL_SHELL_TASK
#define MYNEWT_VAL_SHELL_TASK (1)
#endif

/*** sys/stats/full */
#ifndef MYNEWT_VAL_STATS_CLI
#define MYNEWT_VAL_STATS_CLI (0)
#endif

#ifndef MYNEWT_VAL_STATS_NAMES
#define MYNEWT_VAL_STATS_NAMES (1)
#endif

#ifndef MYNEWT_VAL_STATS_NEWTMGR
#define MYNEWT_VAL_STATS_NEWTMGR (0)
#endif

#endif
